services:

  postgres:

    image: postgres:17

    container_name: postgres

    hostname: postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:

      POSTGRES_DB: ${POSTGRES_DB}

      POSTGRES_USER: ${POSTGRES_USER}

      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:

      - "${POSTGRES_PORT}:5432"

    volumes:

      - postgres-data:/var/lib/postgresql/data

      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d

      - ./infrastructure/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf

      - ./infrastructure/postgres/backups:/backups

    command:

      - postgres

      - -c

      - config_file=/etc/postgresql/postgresql.conf

    healthcheck:

      test:

        [

          "CMD-SHELL",

          "pg_isready -U ${POSTGRES_USER}"

        ]

      interval: 10s

      timeout: 5s

      retries: 5

    networks:

      - backend-network
  


  redis:
    image: redis:7.4-alpine

    container_name: redis

    hostname: redis

    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

    volumes:
      - redis-data:/data
      - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend-network

  