"""add organization_id to roles

Revision ID: c9a046923483
Revises: 4504bf33ac33
Create Date: 2026-08-06 04:50:04.886110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c9a046923483'
down_revision: Union[str, Sequence[str], None] = '4504bf33ac33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_foreign_key(None, 'roles', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'organization_id')
    # ### end Alembic commands ###
