########################################
# NETWORK
########################################

bind 0.0.0.0

protected-mode yes

port 6379

########################################
# PERSISTENCE
########################################

appendonly yes

appendfilename "appendonly.aof"

########################################
# MEMORY
########################################

maxmemory 512mb

maxmemory-policy allkeys-lru

########################################
# LOGGING
########################################

loglevel notice