listen_addresses='*'

max_connections=200

shared_buffers=256MB

effective_cache_size=1GB

maintenance_work_mem=128MB

checkpoint_completion_target=0.9

wal_buffers=16MB

default_statistics_target=100

log_connections=on

log_disconnections=on

log_statement=ddl

logging_collector=on

log_destination=stderr